// <auto-generated />
using System;
using Messager.DAL.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Messager.Migrations
{
    [DbContext(typeof(DAL.DataBase.MessagerDataBase))]
    [Migration("20241008105108_MessagerDataBase")]
    partial class MessagerDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Messager.DAL.Entity.MessageDataBaseEntity", b =>
                {
                    b.Property<Guid>("MessegeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessegeID");

                    b.ToTable("MessageDataBase");
                });

            modelBuilder.Entity("Messager.DAL.Entity.UserDataBaseEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserDataBase");
                });

            modelBuilder.Entity("Messager.DAL.Entity.UserFriendsDataBaseEntity", b =>
                {
                    b.Property<Guid>("FriendID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserDataBaseEntityUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FriendID");

                    b.HasIndex("UserDataBaseEntityUserId");

                    b.ToTable("UserFriendsDataBase");
                });

            modelBuilder.Entity("Messager.DAL.Entity.UserFriendsDataBaseEntity", b =>
                {
                    b.HasOne("Messager.DAL.Entity.UserDataBaseEntity", null)
                        .WithMany("FriendEnt")
                        .HasForeignKey("UserDataBaseEntityUserId");
                });

            modelBuilder.Entity("Messager.DAL.Entity.UserDataBaseEntity", b =>
                {
                    b.Navigation("FriendEnt");
                });
#pragma warning restore 612, 618
        }
    }
}
